# Generated by Django 4.0.3 on 2022-03-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('srno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=500)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
